/**
 * SePay webhook verification helpers.
 *
 * Authorization header format: "Apikey YOUR_API_KEY"
 * OrderCode format: TLS-YYYYMMDD-XXXX  (generated by generateOrderCode())
 *
 * Two-step verification:
 *   1. checkSePayAuth()    — verifies API key in Authorization header. Call first; 401 on fail.
 *   2. parseSePayPayload() — extracts orderCode from payload. Failures are benign skips (200).
 */

export interface SePayPayload {
  id: string | number
  gateway: string
  transactionDate: string
  accountNumber: string
  code: string | null
  content: string
  transferType: string         // "in" | "out"
  transferAmount: number
  referenceCode: string | null
  description: string
}

export interface SePayParseResult {
  ok: boolean
  orderCode?: string
  amount?: number
  transactionId?: string
  referenceCode?: string
  skipReason?: string
}

// MB Bank strips hyphens from transfer content, so we match both:
//   TLS-20260516-7918  (with dashes, from QR/manual)
//   TLS202605167918    (without dashes, as MB Bank sends to SePay)
// Groups: (date 8 digits)(suffix digits) — used to normalize back to canonical form.
const ORDER_CODE_RE = /TLS-?(\d{8})-?(\d+)/i

/**
 * Step 1 — Auth check.
 * Returns true only when Authorization header exactly matches "Apikey <apiKey>".
 * apiKey is loaded server-side from DB (encrypted) or SEPAY_API_KEY env var.
 * Never log apiKey.
 */
export function checkSePayAuth(
  authorizationHeader: string | null,
  apiKey: string
): boolean {
  if (!apiKey) return false
  return authorizationHeader === `Apikey ${apiKey}`
}

/**
 * Step 2 — Payload parse (call only after auth passes).
 * Returns ok=false with a skipReason for benign cases (out transfer, no orderCode).
 * Caller should return HTTP 200 on skip.
 */
export function parseSePayPayload(payload: unknown): SePayParseResult {
  if (!payload || typeof payload !== 'object') {
    return { ok: false, skipReason: 'payload is not an object' }
  }

  const p = payload as SePayPayload

  if (p.transferType !== 'in') {
    return { ok: false, skipReason: `transferType="${p.transferType}" (only "in" is processed)` }
  }

  // Search content, code, then description — SePay may put orderCode in any of these
  const sources = [p.content, p.code, p.description].filter(Boolean).join(' ')
  const match = sources.match(ORDER_CODE_RE)

  if (!match) {
    return {
      ok: false,
      skipReason: `no TLS-YYYYMMDD-XXXX orderCode found in: content="${p.content}" code="${p.code}" description="${p.description}"`,
    }
  }

  // Normalize to canonical TLS-YYYYMMDD-XXXX format (re-inserts dashes stripped by MB Bank)
  const orderCode = `TLS-${match[1]}-${match[2]}`.toUpperCase()
  const amount = p.transferAmount
  const transactionId = String(p.id)

  if (!amount || amount <= 0) {
    return { ok: false, skipReason: `transferAmount invalid: ${p.transferAmount}` }
  }

  return {
    ok: true,
    orderCode,
    amount,
    transactionId,
    referenceCode: p.referenceCode ?? undefined,
  }
}
